steps:
  # 1️⃣ Build Java app
  - name: maven:3.9.6-eclipse-temurin-17
    entrypoint: mvn
    args: ["clean", "package"]

  # 2️⃣ Build Docker image
  - name: gcr.io/cloud-builders/docker
    args:
      [
        "build",
        "-t",
        "us-central1-docker.pkg.dev/$PROJECT_ID/hello-repo/hello-app:$SHORT_SHA",
        "."
      ]

  # 3️⃣ Push Docker image
  - name: gcr.io/cloud-builders/docker
    args:
      [
        "push",
        "us-central1-docker.pkg.dev/$PROJECT_ID/hello-repo/hello-app:$SHORT_SHA"
      ]

  # 4️⃣ Update GitOps repo ggg
  - name: alpine/git
    entrypoint: sh
    args:
      - -c
      - |
        git clone https://github.com/angs-skype/hello-gitops.git
        cd hello-gitops
        sed -i "s|image:.*|image: us-central1-docker.pkg.dev/$PROJECT_ID/hello-repo/hello-app:$SHORT_SHA|" deployment.yaml
        git config user.email "ci@cloudbuild"
        git config user.name "cloudbuild"
        git commit -am "Update image to $SHORT_SHA"
        git push

images:
  - "us-central1-docker.pkg.dev/$PROJECT_ID/hello-repo/hello-app:$SHORT_SHA"

options:
  logging: CLOUD_LOGGING_ONLY
