steps:
  # 1️⃣ Build app
  - name: maven:3.9.6-eclipse-temurin-17
    entrypoint: mvn
    args: ["clean", "package"]

  # 2️⃣ Build Docker image
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - -t
      - us-central1-docker.pkg.dev/$PROJECT_ID/hello-repo/hello-app:$SHORT_SHA
      - .

  # 3️⃣ Push image
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - us-central1-docker.pkg.dev/$PROJECT_ID/hello-repo/hello-app:$SHORT_SHA

  # 4️⃣ Update GitOps repooo
  - name: alpine/git
    entrypoint: sh
    secretEnv: ["GITHUB_TOKEN"]
    args:
      - -c
      - |
        git clone https://$$GITHUB_TOKEN@github.com/angs-skype/hello-gitops.git
        cd hello-gitops
        sed -i "s|image:.*|image: us-central1-docker.pkg.dev/$PROJECT_ID/hello-repo/hello-app:$SHORT_SHA|" deployment.yaml
        git config user.email "ci@cloudbuild"
        git config user.name "cloudbuild"
        git commit -am "Update image to $SHORT_SHA"
        git push

images:
  - us-central1-docker.pkg.dev/$PROJECT_ID/hello-repo/hello-app:$SHORT_SHA

availableSecrets:
  secretManager:
    - versionName: projects/$PROJECT_ID/secrets/github-token/versions/latest
      env: GITHUB_TOKEN

options:
  logging: CLOUD_LOGGING_ONLY
